CREATE OR REPLACE TEMP TABLE TEMP_CRICKET_MATCHES
LIKE CRICKET_MATCHES;

COPY INTO TEMP_CRICKET_MATCHES
FROM @CRICKET_STAGE/clean/{{ params.india_date }}/
FILE_FORMAT = (TYPE = PARQUET)
PATTERN='.*[.]parquet'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

MERGE INTO CRICKET_MATCHES t
USING (
    SELECT DISTINCT *
    FROM TEMP_CRICKET_MATCHES
) s
ON t.MATCH_ID = s.MATCH_ID
AND t.FETCH_DATE = s.FETCH_DATE

WHEN MATCHED THEN
UPDATE SET
    TEAM_1 = s.TEAM_1,
    TEAM_2 = s.TEAM_2,
    MATCH_NAME = s.MATCH_NAME,
    MATCHTYPE = s.MATCHTYPE,
    STATUS = s.STATUS,
    MATCH_DATE = s.MATCH_DATE,
    VENUE_NAME = s.VENUE_NAME,
    CITY = s.CITY,
    DATETIMEGMT = s.DATETIMEGMT,
    MATCHSTARTED = s.MATCHSTARTED,
    MATCHENDED = s.MATCHENDED

WHEN NOT MATCHED THEN
INSERT (
    MATCH_ID,
    TEAM_1,
    TEAM_2,
    MATCH_NAME,
    MATCHTYPE,
    STATUS,
    MATCH_DATE,
    VENUE_NAME,
    CITY,
    DATETIMEGMT,
    MATCHSTARTED,
    MATCHENDED,
    FETCH_DATE
)
VALUES (
    s.MATCH_ID,
    s.TEAM_1,
    s.TEAM_2,
    s.MATCH_NAME,
    s.MATCHTYPE,
    s.STATUS,
    s.MATCH_DATE,
    s.VENUE_NAME,
    s.CITY,
    s.DATETIMEGMT,
    s.MATCHSTARTED,
    s.MATCHENDED,
    s.FETCH_DATE
);
