CREATE OR REPLACE TEMP TABLE TEMP_CRICKET_SCORE
LIKE CRICKET_SCORE;

COPY INTO TEMP_CRICKET_SCORE
FROM @CRICKET_STAGE/score/{{ params.india_date }}/
FILE_FORMAT = (TYPE = PARQUET)
PATTERN='.*[.]parquet'
MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

MERGE INTO CRICKET_SCORE t
USING (
    SELECT DISTINCT *
    FROM TEMP_CRICKET_SCORE
) s
ON t.MATCH_ID = s.MATCH_ID
AND t.INNINGS_ORDER = s.INNINGS_ORDER

WHEN MATCHED THEN
UPDATE SET
    TEAM_NAME = s.TEAM_NAME,
    RUNS = s.RUNS,
    WICKETS = s.WICKETS,
    OVERS = s.OVERS

WHEN NOT MATCHED THEN
INSERT (
    MATCH_ID,
    INNINGS_ORDER,
    TEAM_NAME,
    RUNS,
    WICKETS,
    OVERS
)
VALUES (
    s.MATCH_ID,
    s.INNINGS_ORDER,
    s.TEAM_NAME,
    s.RUNS,
    s.WICKETS,
    s.OVERS
);
